github:itswadesh # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon:itswadesh # Replace with a single Patreon username
open_collective:itswadesh # Replace with a single Open Collective username
ko_fi:itswadesh # Replace with a single Ko-fi username

