# Typical File for extension: vscode-graphql & CodeGen!
projects:
  default:
    schema:
      - ./src/lib/graphql/schema.json # or https://localhost:3777/graphql
    documents:
      - '**/*.gql'
    extensions:
      endpoints:
        default:
          url: https://localhost:3000/graphql
      codegen:
        generates:
          ./src/lib/graphql/_kitql/graphqlTypes.ts:
            plugins:
              - typescript
              - typescript-operations
              - typed-document-node
              - typescript-document-nodes

          ./src/lib/graphql/_kitql/graphqlStores.ts:
            plugins:
              - '@kitql/graphql-codegen'
            config:
              importBaseTypesFrom: $lib/graphql/_kitql/graphqlTypes
              operationPrefix: 'KQL_'

        config:
          useTypeImports: true
